//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gogobuy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tWishProduct
    {
        public int fProductID { get; set; }
        public string fCategory { get; set; }
        public string fProductName { get; set; }
        public Nullable<decimal> fPrice { get; set; }
        public Nullable<int> fQuantity { get; set; }
        public string fImgPath { get; set; }
        public string fDescription { get; set; }
        public Nullable<int> fMemberID { get; set; }
        public string fCity { get; set; }
        public Nullable<System.DateTime> fArrivalTime { get; set; }
        public Nullable<decimal> fCommission { get; set; }
        public Nullable<System.DateTime> fUpdateTime { get; set; }
    
        public virtual tMembership tMembership { get; set; }
    }
}
